kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: copper
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    - name: alert-emailer
      email_configs:
      #- to: demo@devopscube.com
      - to: tharanga.rajapaksha@gmail.com
        send_resolved: false
        #from: from-email@email.com
        #smarthost: email-host-here
        from: tharanga.rajapaksha@gmail.com
        smarthost: smtp.gmail.com
        require_tls: false
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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sz4Qk
        channel: '#devopscube-demo'
