kind: Service
apiVersion: v1
metadata:
  name: emailserver
spec:
  type: LoadBalancer
  selector:
    app: emailserver
  ports:
    #- protocol: "TCP"
    #  port: 25
    #  targetPort: 25
    - protocol: TCP
      port: 25
      targetPort: 25
      name: smtp
      #nodePort: 30025
    - protocol: TCP
      port: 143
      targetPort: 143
      name: imap
      #nodePort: 30143
    - protocol: TCP
      port: 587
      targetPort: 587
      name: submission
    - protocol: TCP
      port: 4190
      targetPort: 4190
      name: sieve
    - protocol: TCP
      port: 11334
      targetPort: 11334
      name: rspamd
      #nodePort: 31334
  #type: NodePort
---        
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: emailserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: emailserver
        track: stable
    spec:
      containers:
        - name: emailserver
        #   image: anuudb/email_server_k8s
          image: tharangarajapaksha/emailserver
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 25
            - name: health
              containerPort: 25
          resources:
            limits:
              cpu: 0.5
              memory: "500Mi"