kind: Service
apiVersion: v1
metadata:
  name: "email"
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: email
  ports:
    #- protocol: "TCP"
    #  port: 25
    #  targetPort: 25
    - protocol: TCP
      port: 25
      targetPort: 25
      name: smtp
      #nodePort: 30025
    - protocol: TCP
      port: 143
      targetPort: 143
      name: imap
      #nodePort: 30143
    - protocol: TCP
      port: 587
      targetPort: 587
      name: submission
    - protocol: TCP
      port: 4190
      targetPort: 4190
      name: sieve
    - protocol: TCP
      port: 11334
      targetPort: 11334
      name: rspamd
      #nodePort: 31334
  #type: NodePort
---        
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: email
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: email
        track: stable
    spec:
      containers:
        - name: email
          image: emailserver
          #image: tharangarajapaksha/emailserver
          #image: lsflk/copper:emailserver
          #imagePullPolicy: Always
          imagePullPolicy: Never
          #command: ["/bin/sh"]
          #args: ["-c", "service postfix start"]
          #args: ["-c", "while true; do echo hello; sleep 10;done"]
          ports:
            - name: submission
              containerPort: 587
            - name: imap
              containerPort: 143
            - name: smtp
              containerPort: 25
            - name: seive
              containerPort: 4190
            - name: rspamd
              containerPort: 11334
            - name: health
              containerPort: 26
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "service rsyslog start 2> /dev/null || true && service postfix start 2> /dev/null || true && service dovecot restart 2> /dev/null || true && service rspamd start 2> /dev/null || true"]
                #command: ["/bin/sh", "-c", "service postfix start"]
                #command: ["/bin/sh", "-c", "pod_start.sh"]
                #command: ['/bin/sh', 'pod_start.sh']
          #lifecycle:
            #postStart:
              #exec:
                #command: ["/bin/sh"]
                #args: ["-c", "service postfix start"]
          env:
                - name: TELEGRAF_VERSION
                  value: "1.8.1-1"
                - name: MYSQL_USER
                  value: "groupoffice"
                - name: MYSQL_PASSWORD
                  value: "groupoffice"
                - name: MYSQL_DATABASE
                  value: "groupoffice"
                - name: EMAIL
                  value: "admin@copper.opensource.lk"
                - name: HOSTNAME
                  value: "mail.copper.opensource.lk"
                - name: FQDN
                  value: "mail.copper.opensource.lk"
                - name: DOMAIN
                  value: "copper.opensource.lk"
                - name: REDIS_HOST
                  value: "REDIS_HOST"
                - name: REDIS_PORT
                  value: "REDIS_PORT"
                - name: DEBUG
                  value: "true"
                - name: RSPAMD_PASSWORD
                  value: "postfix@123"
                - name: CN
                  value: "admin"
                - name: DC1
                  value: "copper"
                - name: DC2
                  value: "opensource"
                - name: DC3
                  value: "lk"
                - name: DNPASS
                  value: "admin"
                - name: OU
                  value: "Users"
                - name: LDAP_HOST_IP
                  value: "ldap-service"
                - name: KEY_PATH
                  value: "KEY_PATH"
                  #value: "Example Inc."
          resources:
            limits:
              #cpu: 0.5
              #memory: "500Mi"
              cpu: 400m # ~4/10th of a core
              memory: "500Mi" # 500 Mebibytes 
      #command: ["/bin/sh"]
      #  args: ["-c", "service postfix start"]  
   
              