apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpldapadmin
  name: phpldapadmin-service
spec:
  ports:
    - port: 443
      nodePort: 300443
  selector:
    app: phpldapadmin
  type: NodePort
