apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service  
    metadata:
      namespace: copper
      labels:
        app: ldap
      name: ldap
    spec:
      type: LoadBalancer
      #loadBalancerIP: 10.10.10.10
      #loadBalancerIP: "YOUR.IP.ADDRESS.HERE"
      #type: ExternalName
      #externalName: copper.ldap.org
      #externalIPs:
      #- 10.1.1.11
      ports:
        - protocol: TCP
          port: 389
          targetPort: 389
          name: ldap
          #nodePort: 30025
        #- protocol: TCP
        #  port: 143
        #  targetPort: 143
        #  name: imap
        #  nodePort: 30143
      #ports:
        #- port: 389
      selector:
        app: ldap
  #  ---
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: ldap
      namespace: copper
      labels:
        app: ldap
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: ldap
        spec:
          hostname: copper-ldap
          containers:
            - name: ldap
              #image: lsflk/copper:openldap
              image: osixia/openldap:1.2.2 # 1.2.3 has a issue so downgraded to 1.2.2
              imagePullPolicy: Always
              volumeMounts:
                - name: ldap-data
                  mountPath: /var/lib/ldap
                - name: ldap-config
                  mountPath: /etc/ldap/slapd.d
                - name: ldap-certs
                  mountPath: /container/service/slapd/assets/certs
              ports:
                - containerPort: 389
                  name: openldap
              env:
                 - name: LDAP_LOG_LEVEL
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_LOG_LEVEL
                 - name: LDAP_ORGANISATION
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_ORGANISATION
                 - name: LDAP_DOMAIN
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_DOMAIN
                 - name: LDAP_ADMIN_PASSWORD
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_ADMIN_PASSWORD
                 - name: LDAP_CONFIG_PASSWORD
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_CONFIG_PASSWORD
                 - name: LDAP_READONLY_USER
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_READONLY_USER
                 - name: LDAP_READONLY_USER_USERNAME
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_READONLY_USER_USERNAME
                 - name: LDAP_READONLY_USER_PASSWORD
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_READONLY_USER_PASSWORD         
                 - name: LDAP_RFC2307BIS_SCHEMA
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_RFC2307BIS_SCHEMA
                 - name: LDAP_BACKEND
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_BACKEND
                 - name: LDAP_TLS # check disabling this to support emailserver
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_TLS
                 - name: LDAP_TLS
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_TLS  
                 - name: LDAP_TLS_CRT_FILENAME
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_TLS_CRT_FILENAME      
                 - name: LDAP_TLS_KEY_FILENAME
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_TLS_KEY_FILENAME
                 - name: LDAP_TLS_CA_CRT_FILENAME 
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_TLS_CA_CRT_FILENAME 
                 - name: LDAP_TLS_ENFORCE
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_TLS_ENFORCE
                 - name: LDAP_TLS_CIPHER_SUITE
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_TLS_CIPHER_SUITE
                 - name: LDAP_TLS_VERIFY_CLIENT
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_TLS_VERIFY_CLIENT
                 - name: LDAP_REPLICATION
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_REPLICATION
                #- name: LDAP_REPLICATION_CONFIG_SYNCPROV
                #    valueFrom:
                #       secretKeyRef:
                #          name: email-secret
                #          key: LDAP_REPLICATION_CONFIG_SYNCPROV
                #
                # - name: LDAP_REPLICATION_CONFIG_SYNCPROV
                #   value: "binddn=\"cn=admin,cn=config\" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase=\"cn=config\" type=refreshAndPersist retry=\"60 +\" timeout=1 starttls=critical"
                # - name: LDAP_REPLICATION_DB_SYNCPROV
                #   value: "binddn=\"cn=admin,$LDAP_BASE_DN\" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase=\"$LDAP_BASE_DN\" type=refreshAndPersist interval=00:00:00:10 retry=\"60 +\" timeout=1 starttls=critical"
                # - name: LDAP_REPLICATION_HOSTS
                #   value: "#PYTHON2BASH:['ldap://ldap-one-service', 'ldap://ldap-two-service']"
                 - name: KEEP_EXISTING_CONFIG
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: KEEP_EXISTING_CONFIG
                 - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_REMOVE_CONFIG_AFTER_SETUP
                 - name: LDAP_SSL_HELPER_PREFIX
                   valueFrom:
                       secretKeyRef:
                          name: email-secret
                          key: LDAP_SSL_HELPER_PREFIX
          volumes:
            - name: ldap-data
              hostPath:
                path: "/data/ldap/db"
            - name: ldap-config
              hostPath:
                path: "/data/ldap/config"
            - name: ldap-certs
              hostPath:
                #path: "/data/ldap/certs"
                #path: "/Users/wso2/Documents/copper/copper/copper-server/kubernetes/tls"
                path: "/tls"
               