version: '2'

services:
    reverseproxy:
        image: reverseproxy:latest
        ports:
            - 8080:8080
        restart: always

    test:
        image: joatmon08/testapp:latest
restart: always
