apiVersion: v1
kind: Service
metadata:
  namespace: copper
  name: mysql
#spec:
#  type: LoadBalancer
#  ports:
#    - protocol: TCP
#      port: 3306
#      targetPort: 3306
#      name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: copper
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: lsflk/copper:mysql
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: c0pperDB
        - name: MYSQL_DATABASE
          value: groupoffice
        ports:
        - containerPort: 3306
        #- containerPort: 36
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:      
           limits:
             cpu: 200m # ~2/10th of a core
             memory: "500Mi" # 500 Mebibytes 
             #memory: 3Gi
           #requests:
             #cpu: 100m
             #memory: 2Gi
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

