{
 "title": "Elastic",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Received mails",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "message:\"*status=sent*\" AND log.file.path:\"/var/log/mail.log\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Received mail count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "dashboard.hits",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "message:\"*status=sent*\" AND log.file.path:\"/var/log/mail.log\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bounced mails",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message:*Host or domain name not found* AND host.name:email AND log.file.path:\"/var/log/mail.log\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bounced mail count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 8 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message:*Host or domain name not found* AND host.name:email AND log.file.path:\"/var/log/mail.log\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Spam counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message:*spam* AND host.name:email AND log.file.path:\"/var/log/mail.log\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "message:*spam* AND host.name:email AND log.file.path:\"/var/log/mail.log\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}