# RBAC authn and authz
apiVersion: v1
kind: ServiceAccount
metadata:
  #name: elasticsearch-logging
  name: elasticsearch
  namespace: copper
  labels:
    #k8s-app: elasticsearch-logging
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  #name: elasticsearch-logging
  name: elasticsearch
  labels:
    #k8s-app: elasticsearch-logging
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: copper
  #name: elasticsearch-logging
  name: elasticsearch
  labels:
    #k8s-app: elasticsearch-logging
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  #name: elasticsearch-logging
  name: elasticsearch
  namespace: copper
  apiGroup: ""
roleRef:
  kind: ClusterRole
  #name: elasticsearch-logging
  name: elasticsearch
  apiGroup: ""
---
# Elasticsearch deployment itself
apiVersion: apps/v1
kind: StatefulSet
metadata:
  #name: elasticsearch-logging
  name: elasticsearch
  namespace: copper
  labels:
    #k8s-app: elasticsearch-logging
    k8s-app: elasticsearch
    #version: v6.2.4
    version: v6.7.1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  #serviceName: elasticsearch-logging
  serviceName: elasticsearch
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      #k8s-app: elasticsearch-logging
      k8s-app: elasticsearch
      #version: v6.2.4
      version: v6.7.1
  template:
    metadata:
      labels:
        #k8s-app: elasticsearch-logging
        k8s-app: elasticsearch
        #version: v6.2.4
        version: v6.7.1
        kubernetes.io/cluster-service: "true"
    spec:
      #serviceAccountName: elasticsearch-logging
      serviceAccountName: elasticsearch
      containers:
      #- image: k8s.gcr.io/elasticsearch:v6.2.4
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
        #name: elasticsearch-logging
        imagePullPolicy: Always
        name: elasticsearch
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        #- name: elasticsearch-logging
        - name: elasticsearch
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      #- name: elasticsearch-logging
      - name: elasticsearch
        emptyDir: {}
      # Elasticsearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: alpine:3.6
        #command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=302144"]
        #name: elasticsearch-logging-init
        name: elasticsearch-init
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  #name: elasticsearch-logging
  name: elasticsearch
  namespace: copper
  labels:
    #k8s-app: elasticsearch-logging
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  type: NodePort # allowing access from localhost machine from nodeport
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
    nodePort: 31335 # this should be removed when we are not useing nodeport
  selector:
    #k8s-app: elasticsearch-logging
    k8s-app: elasticsearch
