apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-image-deployment
  labels:
    app: my-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-image
  template:
    metadata:
      labels:
        app: my-image
    spec:
      containers:
      - name: my-image
        image: my-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
