apiVersion: v1
kind: Secret
metadata:
    name: email-secret
    namespace: monitoring
type: Opaque
stringData:
    TELEGRAF_VERSION: 1.8.1-1
    MYSQL_DATABASE: database
    MYSQL_PASSWORD: password
    PHPLDAPADMIN_LDAP_HOSTS: ldap-service
    PHPLDAPADMIN_SERVER_ADMIN: admin
    PHPLDAPADMIN_SERVER_PATH: /phpldapadmin
    PHPLDAPADMIN_HTTPS: "true"
    PHPLDAPADMIN_HTTPS_CRT_FILENAME: cert.crt
    PHPLDAPADMIN_HTTPS_KEY_FILENAME: cert.key
    PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: ca.crt
    PHPLDAPADMIN_LDAP_CLIENT_TLS: "true"
    PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: try
    PHPLDAPADMIN_LDAP_CLIENT_TLS_CRT_FILENAME: cert.crt
    PHPLDAPADMIN_LDAP_CLIENT_TLS_KEY_FILENAME: cert.key
    PHPLDAPADMIN_LDAP_CLIENT_TLS_CA_CRT_FILENAME: ca.crt
    LDAP_LOG_LEVEL: -1
    LDAP_ORGANISATION: copper.opensource.lk
    LDAP_DOMAIN: copper.opensource.lk
    LDAP_ADMIN_PASSWORD: admin
    LDAP_CONFIG_PASSWORD: admin
    LDAP_READONLY_USER: "true"
    LDAP_READONLY_USER_USERNAME: readonly
    LDAP_READONLY_USER_PASSWORD: readonly
    LDAP_RFC2307BIS_SCHEMA: "false"
    LDAP_BACKEND: mdb
    LDAP_TLS: "true"
    LDAP_TLS_CRT_FILENAME: cert.pem
    LDAP_TLS_KEY_FILENAME: privkey.pem
    LDAP_TLS_CA_CRT_FILENAME : fullchain.pem
    LDAP_TLS_ENFORCE: "false"
    LDAP_TLS_CIPHER_SUITE: SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC
    LDAP_TLS_VERIFY_CLIENT: try
    LDAP_REPLICATION: "false"
    LDAP_REPLICATION_CONFIG_SYNCPROV: binddn=\"cn=admin,cn=config\" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase=\"cn=config\" type=refreshAndPersist retry=\"60 +\" timeout=1 starttls=critical
    LDAP_REPLICATION_DB_SYNCPROV: binddn=\"cn=admin,$LDAP_BASE_DN\" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase=\"$LDAP_BASE_DN\" type=refreshAndPersist interval=00:00:00:10 retry=\"60 +\" timeout=1 starttls=critical
    KEEP_EXISTING_CONFIG: "false"
    LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
    LDAP_SSL_HELPER_PREFIX: "ldap"


    CN : admin
    DC1 : tharanga
    DC2 : seewave
    DC3 : com
    DNPASS : admin
    OU : Users
    LDAP_HOST_IP : ldap-service
    KEY_PATH : KEYPATH
    EMAIL : admin@tharanga.seewave.com
    HOSTNAME : mail.tharanga.seewave.com
    FQDN : mail.tharanga.seewave.com
    DOMAIN : tharanga.seewave.com
    REDIS_HOST : REDIS_HOST
    REDIS_PORT : REDIS_PORT
    DEBUG : "true"
    RSPAMD_PASSWORD : spam
