apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: copper-ingress
  namespace: copper
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/ssl-services: "copperclient"
    nginx.org/ssl-services: "hello-world-svc"
    nginx.org/ssl-services: "groupoffice"
    ingress.kubernetes.io/ssl-redirect: “true”
spec:
  tls:
    - hosts:
      #- example.com
      - copper.opensource.lk
      secretName: tls-certificate
  rules:
  #- host: example.com
  - host: copper.opensource.lk
    http:
      paths:
      - path: /hello
        backend:
          serviceName: hello-world-svc
          servicePort: 8080
      - path: /
        backend:
          serviceName: groupoffice
          servicePort: 8008
      - path: /cu
        backend:
          serviceName: copperclient
          servicePort: 4443
      - path: /phpldapadmin
        backend:
          serviceName: phpldapadmin
          servicePort: 8088
      - path: /site/service/
        backend:
          serviceName: ldap-pw
          servicePort: 8888
          