FROM osixia/openldap:1.2.1
MAINTAINER Your Name <LSF>

ADD ./openldap/bootstrap /container/service/slapd/assets/config/bootstrap
ADD ./openldap/certs /container/service/slapd/assets/certs
ADD ./openldap/environment /container/environment/01-custom
