kind: Service
apiVersion: v1
metadata:
  name: "rainloop"
spec:
  selector:
    app: "rainloop"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      clusterIP: None
      #nodePort: 88
