kind: Service
apiVersion: v1
metadata:
  name: groupoffice
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: groupoffice
  ports:
    #- protocol: "TCP"
    #  port: 443
    - protocol: TCP
      port: 8004
      targetPort: 80
      name: http
    #- protocol: TCP
    #  port: 433
    #  targetPort: 433
    #  name: http
    #- protocol: TCP
    #  port: 587
    #  targetPort: 587
    #  name: submission
    #- protocol: TCP
    #  port: 143
    #  targetPort: 143
      #targetPort: http
      #clusterIP: None    
    #  name: imap
      #nodePort: 30080
  #type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: groupoffice
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: groupoffice
        track: stable
    spec:
      containers:
        - name: groupoffice
          image: "intermesh/groupoffice"
          #image: groupoffice
          #imagePullPolicy: Never
          env:
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "c0pperDB"
            - name: MYSQL_DATABASE
              value: "groupoffice"
            - name: MYSQL_HOST
              value: "mysql"
          ports:
            - name: http
              containerPort: 80
            #- name: submission
            #  containerPort: 587
            - name: health
              containerPort: 81
          #resources:      
          # limits:
          #   cpu: 800m
             #cpu: "2"
             #memory: 2Gi
             #memory: 1Gi # once we remove memory limits it can grown untill host permits.
             #memory: 512Mi
          # requests:
          #   cpu: 800m
             #memory: 1Gi # 1Gi is not enough for horde
             #memory: 256Mi
          #dnsPolicy: ClusterFirst # errors with this version
          #restartPolicy: Never   # errors with this version
          resources:
             limits:
               cpu: 500m # ~4/10th of a core
               memory: "700Mi" # 900 Mebibytes  
          #  limits:
          #    cpu: 0.9
          #    memory: "5500Mi"
          #livenessProbe:
          #  httpGet:
          #    path: /healthz
          #    port: 81
          #    scheme: HTTP
          #  initialDelaySeconds: 5
          #  periodSeconds: 15
          #  timeoutSeconds: 5
          #readinessProbe:
          #  httpGet:
          #    path: /readiness
          #    port: 81
          #    scheme: HTTP
          #  initialDelaySeconds: 5
          #  timeoutSeconds: 1
          